Repository orbinson/aem-groovy-console, pull requests merged in 2022-12, with the labels that each got.

#1 Run script on all AEM instances
  .run/Author.run.xml
  .run/Publish.run.xml
  .run/[author] aem-groovy-console.run.xml
  .run/[author] all.run.xml
  .run/[author] bundle.run.xml
  .run/[author] ui.apps.run.xml
  .run/[author] ui.config.run.xml
  .run/[author] ui.content.run.xml
  .run/[publish] aem-groovy-console.run.xml
  .run/[publish] all.run.xml
  .run/[publish] bundle.run.xml
  .run/[publish] ui.apps.run.xml
  .run/[publish] ui.config.run.xml
  .run/[publish] ui.content.run.xml
  README.md
  all/pom.xml
  bundle/pom.xml
  bundle/src/main/groovy/org/cid15/aem/groovy/console/api/impl/ResourceScriptContext.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/components/Toolbar.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/configuration/ConfigurationService.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/configuration/impl/DefaultConfigurationService.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/constants/GroovyConsoleConstants.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/extension/impl/DefaultScriptMetaClassExtensionProvider.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/replication/ReplicatedScriptListener.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/response/ReplicateScriptResponse.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/response/impl/DefaultReplicateScriptResponse.groovy
  bundle/src/main/groovy/org/cid15/aem/groovy/console/servlets/ReplicateScriptServlet.groovy
  bundle/src/main/java/org/cid15/aem/groovy/console/configuration/impl/ConfigurationServiceProperties.java
  bundle/src/test/groovy/org/cid15/aem/groovy/console/audit/impl/DefaultAuditServiceSpec.groovy
  bundle/src/test/groovy/org/cid15/aem/groovy/console/impl/DefaultGroovyConsoleServiceSpec.groovy
  pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/clientlibs/js/console.js
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/components/console/methods.html
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/components/console/toolbar.html
  ui.config/pom.xml
  ui.config/src/main/content/META-INF/vault/filter.xml
  ui.config/src/main/content/jcr_root/apps/groovyconsole-config/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-groovyconsole.config
  ui.config/src/main/content/jcr_root/apps/groovyconsole-config/osgiconfig/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-groovy-console.xml
  ui.content/pom.xml
  ui.content/src/main/content/META-INF/vault/filter.xml
  ui.content/src/main/content/jcr_root/_rep_policy.xml
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/.content.xml
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/CreateOsgiConfigurations.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/CreatePackage.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/DeleteOsgiConfigurations.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/FindOrphanedComponents.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/FindPagesWithProperty.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/FindPagesWithTemplate.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/FindReferences.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/FulltextQuery.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/JcrSearch.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/ListTemplates.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/UpdateOsgiConfiguration.groovy
  ui.content/src/main/content/jcr_root/conf/groovyconsole/scripts/samples/UpdatePageTitles.groovy
  ui.content/src/main/content/jcr_root/home/users/system/groovy-console-system-user/.content.xml
  ui.content/src/main/content/jcr_root/var/groovyconsole/.content.xml
  ui.content/src/main/content/jcr_root/var/groovyconsole/audit/.content.xml
  ui.content/src/main/content/jcr_root/var/groovyconsole/audit/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/groovyconsole/scripts/.content.xml
Labels: enhancement

#9 Add 'retrieve=true' to fix datatables error dialog
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/clientlibs/js/audit.js
Labels: duplicate, enhancement

#10 Move groovy extensions bundle to this project
  all/pom.xml
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/builders/AbstractContentBuilder.groovy
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/builders/NodeBuilder.groovy
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/builders/PageBuilder.groovy
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/extension/impl/DefaultBindingExtensionProvider.groovy
Labels: enhancement

#13 Update actions to resolve warnings
  .github/workflows/maven-test.yml
Labels: enhancement

#18 Update links
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/extension/impl/DefaultBindingExtensionProvider.groovy
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/extension/impl/DefaultStarImportExtensionProvider.groovy
  pom.xml
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/components/console/about.html
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/components/console/methods.html
Labels: documentation

#24 Prepare for 18.0.0 release
  .github/workflows/build-and-test-cloud.yml
  .github/workflows/build-and-test-on-prem.yml
  .github/workflows/maven-release-central.yml
  CHANGELOG.md
  bundle/pom.xml
  bundle/src/main/groovy/be/orbinson/aem/groovy/console/extension/impl/DefaultScriptMetaClassExtensionProvider.groovy
  pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/components/console/methods.html
  ui.content/pom.xml
Labels: documentation, enhancement
